apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebpage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mywebpage
  template:
    metadata:
      labels:
        app: mywebpage
    spec:
      containers:
      - name: mywebpage
        image: bbchandru/mywebpage:latest   # 👈 replace if needed
        ports:
        - containerPort: 80